# Autogenerated from C:/projects/SC-CL/llvm-14.0.0.src/tools/clang/tools/extra/clangd/unittests/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
from pathlib import Path
def path(p):
    if not p: return ''
    return str((Path(__file__).parent / p).resolve())

# This is a shim to run the gtest unittests in ../unittests using lit.

config.llvm_libs_dir = "C:/projects/SC-CL/llvm-14.0.0.src/%(build_mode)s/lib"
config.shlibdir = "C:/projects/SC-CL/llvm-14.0.0.src/%(build_mode)s/bin"

config.clangd_source_dir = "C:/projects/SC-CL/llvm-14.0.0.src/tools/clang/tools/extra/clangd/unittests/.."
config.clangd_binary_dir = "C:/projects/SC-CL/llvm-14.0.0.src/tools/clang/tools/extra/clangd/unittests/.."

# Delegate logic to lit.cfg.py.
lit_config.load_config(config, "C:/projects/SC-CL/llvm-14.0.0.src/tools/clang/tools/extra/clangd/unittests/lit.cfg.py")
