# Install script for directory: C:/projects/SC-CL/llvm-14.0.0.src/lib

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/LLVM")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/IR/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/FuzzMutate/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/FileCheck/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/InterfaceStub/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/IRReader/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/CodeGen/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/BinaryFormat/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Bitcode/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Bitstream/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/DWARFLinker/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Extensions/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Frontend/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Transforms/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Linker/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Analysis/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/LTO/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/MC/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/MCA/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Object/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/ObjectYAML/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Option/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Remarks/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Debuginfod/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/DebugInfo/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/DWP/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/ExecutionEngine/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Target/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/AsmParser/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/LineEditor/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/ProfileData/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Passes/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/TextAPI/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/ToolDrivers/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/XRay/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/Testing/cmake_install.cmake")
  include("C:/projects/SC-CL/llvm-14.0.0.src/lib/WindowsManifest/cmake_install.cmake")

endif()

